config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  resource :upload, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phrase.rb
# Phrase is a table containing:
#   1. The words returned from Clairfai API (:words)
#   2. The finished sentence which will be displayed. (:content)

class Phrase < ActiveRecord::Base
  belongs_to :upload
end

app/models/upload.rb
# Upload will deal exclusively with user uploaded image

class Upload < ActiveRecord::Base
  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: 'image/jpeg'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @phrases = Phrase.order('id desc').take(10)
    @upload = Upload.new
    render :index
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def create
    upload = Upload.create(upload_params)
    words = get_clarifai_tags(upload)
    pg = PhraseGenerator.new(words)
    Phrase.create(
      words: words,
      content: pg.perform,
      upload: upload
    )
    redirect_to root_path
  end

  private

  def get_clarifai_tags(upload)
    cl_response = ClarifaiRuby::TagRequest.new.get(upload.image.url)
    cl_response.tag_images[0].tags_by_words.join(' ')
  end

  def upload_params
    params.require(:upload).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.page-header
  .container
    .row-fluid
      .title
        Picture Stories
      .h3
        Upload a picture to generate a sentence based on the picture's content.
    .row-fluid
      .circle
        .container
          .form-container
            = form_for @upload, url: upload_path, class: 'form-group' do |form|
              = form.label :upload_an_image!
              = form.file_field :image, class: 'form-control'
              = form.submit 'upload', class: 'form-control btn btn-primary'

.container
  .row
    - @phrases.each do |p|
      .col-sm-4
        .jumbotron
          .text-center
            .uploaded_time
              Uploaded on
              = p.upload.image_updated_at.strftime("%B %d, %Y")
              <br>
              <br>
            .image

              = link_to image_tag(p.upload.image.url(:thumb), class: 'img-rounded'), p.upload.image.url(:medium)
              <br>
              <br>
            .phrase
              = p.content
              <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageTags</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>